width, height = 1200, 750
button_width = 150
button_height = 70
button_spacing = 30
MY_CAR_HEIGHT = 130
MY_CAR_WIDTH = 65
ENEMY_CAR_HEIGHT = 150
ENEMY_CAR_WIDTH = 140
LIFE_HEART_HEIGHT = 60
LIFE_HEART_WIDTH = 60
my_car_image_x = (width - MY_CAR_WIDTH) // 2  # Center horizontally
my_car_image_y = height - MY_CAR_HEIGHT  # Bottom of the window
position = (0, 0)
